services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: overview
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongodb/db:/data/db
