management.endpoint.health.probes.enabled: true

mongock.change-logs-scan-package: it.achtelik.javaspringtemplate.shares.dbmigration.applications

server.shutdown: graceful
spring:
  webflux:
    base-path: /backend

graphql:
  graphiql.enabled: true
