management.endpoint.health.probes.enabled: true

mongock.change-logs-scan-package: it.achtelik.javaspringtemplate.commons.dbmigration.application

server.shutdown: graceful
spring:
  webflux:
    base-path: /backend
